/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    authors: Author;
    docs: Doc;
    'doc-groups': DocGroup;
    media: Media;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    'doc-groups': DocGroupsSelect<false> | DocGroupsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    pricing: Pricing;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Wird aus „title" erzeugt, wenn leer. Teil der URL — nachträgliche Änderungen brechen bestehende Links.
   */
  slug?: string | null;
  category: 'praxis' | 'produkt' | 'bewertung' | 'datenschutz' | 'fallstudie' | 'didaktik' | 'changelog';
  /**
   * Wie im Design geschrieben, z. B. „7 Min“.
   */
  readingTime?: string | null;
  /**
   * Ein Datum in der Zukunft hält den Beitrag unsichtbar.
   */
  publishedAt: string;
  /**
   * Große Karte oben auf /blog. Setzt das Flag bei allen anderen Beiträgen zurück.
   */
  featured?: boolean | null;
  author: number | Author;
  /**
   * Füllt die Bildplätze blog-featured (Aufmacher) und article-hero (Artikelkopf). Ohne Bild bleibt der beschriftete Platzhalter stehen.
   */
  heroImage?: (number | null) | Media;
  /**
   * Der Text auf der Karte in der Beitragsübersicht.
   */
  excerpt: string;
  /**
   * Erster Absatz des Artikels, größer gesetzt als der Fließtext.
   */
  lead: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Leer lassen heißt: aus dem Inhalt ableiten.
   */
  seo?: {
    /**
     * Ersetzt den Seitentitel im Browser-Tab und in Suchergebnissen.
     */
    title?: string | null;
    /**
     * Rund 150–160 Zeichen werden angezeigt.
     */
    description?: string | null;
    /**
     * Beim Teilen in sozialen Netzwerken. Empfohlen 1200 × 630.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * z. B. „Didaktik & Bewertungsqualität“.
   */
  role?: string | null;
  /**
   * Zwei bis drei Zeichen, erscheinen im runden Avatar.
   */
  initials: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschreibt das Bild für Screenreader und wenn es nicht lädt. Rein dekorative Bilder: kurzen Zweck angeben.
   */
  alt: string;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  title: string;
  /**
   * Wird aus „title" erzeugt, wenn leer. Teil der URL — nachträgliche Änderungen brechen bestehende Links.
   */
  slug?: string | null;
  group: number | DocGroup;
  /**
   * Position in der Seitenleiste des Kapitels.
   */
  order: number;
  /**
   * Erscheint in der Liste auf der Doku-Startseite.
   */
  popular?: boolean | null;
  /**
   * Kleinere Zahl steht weiter oben. Die Liste ist kuratiert — ohne diese Angabe richtet sie sich nach der Kapitel-Reihenfolge.
   */
  popularOrder?: number | null;
  /**
   * Wird über dem Artikel angezeigt.
   */
  updatedOn?: string | null;
  /**
   * z. B. „LMS 2.4 und App 3.1“.
   */
  appliesTo?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Leer lassen heißt: aus dem Inhalt ableiten.
   */
  seo?: {
    /**
     * Ersetzt den Seitentitel im Browser-Tab und in Suchergebnissen.
     */
    title?: string | null;
    /**
     * Rund 150–160 Zeichen werden angezeigt.
     */
    description?: string | null;
    /**
     * Beim Teilen in sozialen Netzwerken. Empfohlen 1200 × 630.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doc-groups".
 */
export interface DocGroup {
  id: number;
  label: string;
  /**
   * Wird aus „label" erzeugt, wenn leer. Teil der URL — nachträgliche Änderungen brechen bestehende Links.
   */
  slug?: string | null;
  /**
   * Kleinere Zahl steht weiter oben.
   */
  order: number;
  /**
   * Erscheint auf der Übersichtskarte der Dokumentation.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingänge aus dem Kontaktformular. Werden nach 12 Monaten gelöscht (siehe Datenschutzerklärung).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  organisation?: string | null;
  teamsize?: ('1' | '2–5' | '6–15' | '16–50' | 'mehr als 50') | null;
  topic?:
    | (
        | 'Demo für meine Schule'
        | 'Testzugang als Einzel-Lehrkraft'
        | 'Angebot Campus / mehrere Standorte'
        | 'Datenschutz & AV-Vertrag'
        | 'Etwas anderes'
      )
    | null;
  message?: string | null;
  /**
   * Ohne Einwilligung nimmt das Formular die Anfrage nicht an.
   */
  consent: boolean;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null)
    | ({
        relationTo: 'doc-groups';
        value: number | DocGroup;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  readingTime?: T;
  publishedAt?: T;
  featured?: T;
  author?: T;
  heroImage?: T;
  excerpt?: T;
  lead?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  initials?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  group?: T;
  order?: T;
  popular?: T;
  popularOrder?: T;
  updatedOn?: T;
  appliesTo?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doc-groups_select".
 */
export interface DocGroupsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  order?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  organisation?: T;
  teamsize?: T;
  topic?: T;
  message?: T;
  consent?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Ziel des „Lernen ↗“-Links in Kopf- und Fußzeile.
   */
  lernenUrl: string;
  /**
   * Noch ein Platzhalter aus dem Design — vor dem Launch ersetzen.
   */
  appStoreUrl?: string | null;
  /**
   * Noch ein Platzhalter aus dem Design — vor dem Launch ersetzen.
   */
  playStoreUrl?: string | null;
  /**
   * Empfänger der Formular-Anfragen; steht auch im Seitenfuß.
   */
  contactEmail: string;
  privacyEmail?: string | null;
  /**
   * Die festen Bildplätze des Designs. Leer bleiben heißt: der beschriftete Platzhalter steht, das Layout ist bereits final. Bitte keine generierten oder Stock-Bilder einsetzen.
   */
  imageSlots?: {
    heroLms?: (number | null) | Media;
    heroApp?: (number | null) | Media;
    homeAblauf?: (number | null) | Media;
    solApp?: (number | null) | Media;
    solLms?: (number | null) | Media;
    aboutHero?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  /**
   * Reihenfolge im Admin ist die Reihenfolge auf der Seite.
   */
  tiers?:
    | {
        /**
         * Kleine Versalien-Zeile, z. B. „Solo“.
         */
        eyebrow: string;
        name: string;
        tagline?: string | null;
        /**
         * Leer lassen für „auf Anfrage“-Tarife.
         */
        monthly?: number | null;
        /**
         * Monatlicher Betrag bei Jahreszahlung.
         */
        yearly?: number | null;
        /**
         * Wird statt der Zahlen angezeigt, z. B. „Individuell“.
         */
        customLabel?: string | null;
        ctaLabel: string;
        /**
         * Grüner Rahmen und die Fahne „Meistgewählt“.
         */
        highlighted?: boolean | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  lernenUrl?: T;
  appStoreUrl?: T;
  playStoreUrl?: T;
  contactEmail?: T;
  privacyEmail?: T;
  imageSlots?:
    | T
    | {
        heroLms?: T;
        heroApp?: T;
        homeAblauf?: T;
        solApp?: T;
        solLms?: T;
        aboutHero?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  tiers?:
    | T
    | {
        eyebrow?: T;
        name?: T;
        tagline?: T;
        monthly?: T;
        yearly?: T;
        customLabel?: T;
        ctaLabel?: T;
        highlighted?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  /**
   * Anführungszeichen mitschreiben, z. B. „…“.
   */
  quote: string;
  /**
   * z. B. „— Kursleitung, Integrationskurs B1, Ulm“.
   */
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  variant: 'note' | 'warning';
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}