import "server-only";
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// S3-compatible presign (PUT/GET) + DeleteObject against the private Cloudflare
// R2 speaking-audio bucket (teacher-lms/02 §11, /04 §4). Key =
// speaking/{class_id}/{submission_id}/{uuid}.m4a — server-generated by the
// submit route. Presigned URLs are short-lived (≤300 s) and NEVER logged/stored.

const EXPIRES_IN = 300; // Sekunden — kurzlebig (Ingest + Whisper-Fetch).

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`${name} not set (R2 not configured)`);
  return v;
}

// Der Client wird pro Aufruf lazy erzeugt — so wirft ein fehlendes Secret erst zur
// Laufzeit (sauberer 503 in der Route), nie beim `next build`-Page-Data-Collect.
function client(): S3Client {
  const accountId = requireEnv("R2_ACCOUNT_ID");
  return new S3Client({
    region: "auto",
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: {
      accessKeyId: requireEnv("R2_ACCESS_KEY_ID"),
      secretAccessKey: requireEnv("R2_SECRET_ACCESS_KEY"),
    },
  });
}

/**
 * Presigned PUT für den Direkt-Upload durch den Client. `contentType` wird als
 * SIGNIERTER Header gepinnt → der Client MUSS exakt diesen Content-Type senden,
 * sonst schlägt die Signatur fehl. Hinweis: presigned PUT kann keine
 * Content-Length-Range hart erzwingen (das könnte nur presigned POST); die
 * ≤20-MB-/≤5-min-Grenze deckt die client-Aufnahme + der Dauer-Guard in
 * /api/speaking/finalize (>5:00 ⇒ 422, Claim zurückgenommen). `maxBytes` bleibt
 * Teil des Vertrags (Doku/Client), wird hier aber nicht in die Signatur gebacken.
 */
export function presignPut(
  key: string,
  opts?: { maxBytes?: number; contentType?: string }
): Promise<string> {
  const cmd = new PutObjectCommand({
    Bucket: requireEnv("R2_BUCKET"),
    Key: key,
    ContentType: opts?.contentType,
  });
  return getSignedUrl(client(), cmd, { expiresIn: EXPIRES_IN });
}

/** Presigned GET — nur serverseitig genutzt (finalize holt die Audio für Whisper). */
export function presignGet(key: string): Promise<string> {
  const cmd = new GetObjectCommand({ Bucket: requireEnv("R2_BUCKET"), Key: key });
  return getSignedUrl(client(), cmd, { expiresIn: EXPIRES_IN });
}

/** Harte Löschung aus R2 (purge-audio-Cron nach audio_purge_at). */
export async function deleteObject(key: string): Promise<void> {
  await client().send(new DeleteObjectCommand({ Bucket: requireEnv("R2_BUCKET"), Key: key }));
}
